version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  hello-world:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            source django-env/Script/activate
            echo "Run env successful."

workflows:
  main:
    jobs:
      - hello-world
