version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  hello-world:
    executor: python/default
    steps:
      - checkout
      - run: echo "Hello World"

workflows:
  main:
    jobs:
      - hello-world
