# Generated by Django 3.0.3 on 2020-02-12 16:03

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='uploads/product-1.jpg', upload_to=shop.models.get_image_path),
        ),
    ]
